ALTER TABLE "Church"
ADD COLUMN "siteUrl" TEXT NOT NULL DEFAULT '',
ADD COLUMN "tagline" TEXT NOT NULL DEFAULT 'A place to belong.',
ADD COLUMN "addressStreet" TEXT NOT NULL DEFAULT '',
ADD COLUMN "phone" TEXT NOT NULL DEFAULT '',
ADD COLUMN "email" TEXT NOT NULL DEFAULT '',
ADD COLUMN "taxId" TEXT NOT NULL DEFAULT '',
ADD COLUMN "enabledModules" JSONB NOT NULL DEFAULT '[]';
