import Link from "next/link";
import { Card, Container } from "@/components/ui";
import { getCurrentUser } from "@/lib/auth";
import { db } from "@/lib/db";

function formatBytes(size: number) {
  if (size < 1024 * 1024) return `${Math.max(1, Math.round(size / 1024))} KB`;
  return `${(size / (1024 * 1024)).toFixed(1)} MB`;
}

export default async function MemberDocumentsPage() {
  const user = await getCurrentUser();
  if (!user) return <main className="py-12"><Container><Card><h1 className="font-serif text-3xl">Sign in required</h1><Link href="/account" className="focus-ring mt-4 inline-block text-coral">Go to account</Link></Card></Container></main>;
  if (!user.permissions.includes("MY_MEMBERSHIP")) return <main className="py-12"><Container><Card><h1 className="font-serif text-3xl">Member documents and forms</h1><p className="mt-4 leading-7 text-ink/60">Membership access is not enabled for this account.</p></Card></Container></main>;
  const link = await db.membershipUserMemberLink.findUnique({ where: { userId: user.id }, select: { individual: { select: { familyId: true } } } });
  if (!link) return <main className="py-12"><Container><Card><h1 className="font-serif text-3xl">Member documents and forms</h1><p className="mt-4 leading-7 text-ink/60">Your account is not linked to a membership record yet. Once your link is approved, shared documents and forms will appear here.</p><Link href="/account/membership" className="focus-ring mt-6 inline-block rounded-full border border-coral px-5 py-3 text-sm font-semibold text-coral">Back to member center</Link></Card></Container></main>;
  const [documents, forms, submissions] = await Promise.all([
    db.membershipDocument.findMany({ where: { familyId: link.individual.familyId, memberVisible: true, OR: [{ expiresAt: null }, { expiresAt: { gt: new Date() } }] }, orderBy: { createdAt: "desc" }, select: { id: true, originalName: true, category: true, description: true, mimeType: true, sizeBytes: true, expiresAt: true, createdAt: true } }),
    db.form.findMany({ where: { enabled: true, status: "PUBLISHED", audience: { in: ["PUBLIC", "MEMBERS"] } }, orderBy: { updatedAt: "desc" }, select: { id: true, name: true, updatedAt: true } }),
    db.formSubmission.findMany({ where: { userId: user.id }, orderBy: { createdAt: "desc" }, take: 25, select: { id: true, createdAt: true, form: { select: { id: true, name: true } } } })
  ]);
  return <main className="py-12 sm:py-16"><Container className="max-w-5xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-coral">Member center</p><h1 className="mt-2 font-serif text-4xl">Documents and forms</h1><p className="mt-3 max-w-2xl leading-7 text-ink/60">Access documents shared with your household and complete forms published by the church.</p></div><Link href="/account/membership" className="focus-ring rounded-full border border-ink/15 px-4 py-2 text-sm font-semibold hover:border-coral hover:text-coral">Back to member center</Link></div>
    <div className="mt-10 grid gap-6 lg:grid-cols-2">    <Card><h2 className="font-serif text-2xl">Shared documents</h2><p className="mt-2 text-sm text-ink/60">Documents shared with your household appear here until they expire.</p><div className="mt-6 grid gap-3">{documents.length ? documents.map((document) => <div key={document.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-ink/10 p-4"><div><p className="font-semibold">{document.originalName}</p><p className="mt-1 text-xs text-ink/55">{document.category} · {document.mimeType} · {formatBytes(document.sizeBytes)}{document.expiresAt ? ` · expires ${document.expiresAt.toLocaleDateString()}` : ""}</p>{document.description && <p className="mt-2 text-sm text-ink/65">{document.description}</p>}</div><a href={`/api/membership/families/${link.individual.familyId}/documents/${document.id}`} className="focus-ring rounded-full bg-coral px-4 py-2 text-sm font-semibold text-white">Download</a></div>) : <p className="text-sm text-ink/60">No documents have been shared with your household.</p>}</div></Card>
      <Card><h2 className="font-serif text-2xl">Forms</h2><p className="mt-2 text-sm text-ink/60">Complete forms published by the church. Your submission is delivered through the form’s configured workflow.</p><div className="mt-6 grid gap-3">{forms.length ? forms.map((form) => <Link key={form.id} href={`/account/membership/documents/forms/${form.id}`} className="focus-ring rounded-xl border border-ink/10 p-4 transition hover:-translate-y-0.5 hover:border-coral/50"><p className="font-semibold">{form.name}</p><p className="mt-1 text-sm text-ink/55">Open form <span aria-hidden="true">→</span></p></Link>) : <p className="text-sm text-ink/60">No forms are currently available.</p>}</div><div className="mt-8 border-t border-ink/10 pt-6"><h3 className="font-serif text-xl">Your submissions</h3><div className="mt-3 grid gap-2">{submissions.length ? submissions.map((submission) => <Link key={submission.id} href={`/account/membership/documents/forms/${submission.form.id}`} className="focus-ring flex items-center justify-between rounded-lg border border-ink/10 px-3 py-2 text-sm"><span>{submission.form.name}</span><span className="text-xs text-ink/55">{submission.createdAt.toLocaleDateString()}</span></Link>) : <p className="text-sm text-ink/60">Your completed submissions will appear here.</p>}</div></div></Card>
    </div>
  </Container></main>;
}
