"use client";
import { useEffect, useState } from "react";
import type { FormEvent } from "react";
import { Container } from "@/components/ui";

export default function SiteSettingsPage() {
  const [settings, setSettings] = useState({ smtpHost: "", smtpPort: 587, smtpUser: "", smtpPassword: "", emailFrom: "", registrationCode: "" });
  const [message, setMessage] = useState("");
  useEffect(() => { void fetch("/api/site-settings").then((response) => response.json()).then((value) => setSettings((current) => ({ ...current, ...value, smtpPassword: "" }))).catch(() => setMessage("Unable to load site settings.")); }, []);
  async function save(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const response = await fetch("/api/site-settings", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(settings) });
    setMessage(response.ok ? "Settings saved." : "Unable to save site settings.");
    if (response.ok) setSettings((current) => ({ ...current, smtpPassword: "", registrationCode: "" }));
  }
  return <main><Container className="py-10 sm:py-14"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-coral">Administration</p><h1 className="mt-2 font-serif text-4xl">Site Settings</h1><p className="mt-3 max-w-2xl text-ink/60">SMTP and registration settings are stored server-side. Passwords and codes are encrypted with the application secret and never returned to the browser.</p><form onSubmit={(event) => void save(event)} className="mt-8 grid max-w-2xl gap-4 rounded-2xl border border-ink/10 bg-white p-6 shadow-sm"><label className="grid gap-1 text-sm font-semibold">SMTP host<input required value={settings.smtpHost} onChange={(event) => setSettings({ ...settings, smtpHost: event.target.value })} className="focus-ring rounded-lg border border-ink/15 px-3 py-2 font-normal" /></label><label className="grid gap-1 text-sm font-semibold">SMTP port<input required type="number" value={settings.smtpPort} onChange={(event) => setSettings({ ...settings, smtpPort: Number(event.target.value) })} className="focus-ring rounded-lg border border-ink/15 px-3 py-2 font-normal" /></label><label className="grid gap-1 text-sm font-semibold">SMTP username<input required value={settings.smtpUser} onChange={(event) => setSettings({ ...settings, smtpUser: event.target.value })} className="focus-ring rounded-lg border border-ink/15 px-3 py-2 font-normal" /></label><label className="grid gap-1 text-sm font-semibold">SMTP password<input type="password" placeholder="Leave blank to keep current" value={settings.smtpPassword} onChange={(event) => setSettings({ ...settings, smtpPassword: event.target.value })} className="focus-ring rounded-lg border border-ink/15 px-3 py-2 font-normal" /></label><label className="grid gap-1 text-sm font-semibold">From address<input required type="email" value={settings.emailFrom} onChange={(event) => setSettings({ ...settings, emailFrom: event.target.value })} className="focus-ring rounded-lg border border-ink/15 px-3 py-2 font-normal" /></label><label className="grid gap-1 text-sm font-semibold">Church registration code<input type="password" placeholder="Leave blank to keep current" value={settings.registrationCode} onChange={(event) => setSettings({ ...settings, registrationCode: event.target.value })} className="focus-ring rounded-lg border border-ink/15 px-3 py-2 font-normal" /></label><button className="focus-ring w-fit rounded-full bg-coral px-5 py-3 text-sm font-semibold text-white" type="submit">Save settings</button>{message && <p role="status" className="text-sm">{message}</p>}</form></Container></main>;
}
