"use client";
import { useEffect, useState } from "react";
import { Button, Notification } from "@/components/ui";

function ListEditor({ label, placeholder, values, onChange }: { label: string; placeholder: string; values: string[]; onChange: (values: string[]) => void }) {
  const [newValue, setNewValue] = useState("");
  return <fieldset className="rounded-xl border border-ink/10 p-4"><legend className="px-1 text-sm font-semibold">{label}</legend><div className="mt-2 flex flex-wrap gap-2">{values.map((value) => <span className="inline-flex items-center gap-2 rounded-full bg-mist px-3 py-1 text-sm" key={value}>{value}<button type="button" className="font-semibold text-coral" onClick={() => onChange(values.filter((item) => item !== value))} aria-label={`Remove ${value}`}>×</button></span>)}</div><div className="mt-3 flex gap-2"><input className="focus-ring min-w-0 flex-1 rounded-lg border border-ink/15 px-3 py-2 text-sm" value={newValue} onChange={(event) => setNewValue(event.target.value)} placeholder={placeholder} /><button type="button" className="focus-ring rounded-full border border-coral px-3 py-2 text-sm font-semibold text-coral" onClick={() => { const value = newValue.trim(); if (value && !values.includes(value)) onChange([...values, value]); setNewValue(""); }}>Add</button></div></fieldset>;
}
export function EventSettingsManager() {
  const [eventTypes, setEventTypes] = useState<string[]>([]); const [categories, setCategories] = useState<string[]>([]); const [locations, setLocations] = useState<string[]>([]); const [timeZone, setTimeZone] = useState("America/Chicago"); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  useEffect(() => { void fetch("/api/events/settings").then((response) => response.json()).then((value) => { if (value.settings) { setEventTypes(value.settings.eventTypes); setCategories(value.settings.categories); setLocations(value.settings.locations); setTimeZone(value.settings.timeZone); } }); }, []);
  async function save() { setError(""); setMessage(""); const response = await fetch("/api/events/settings", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ eventTypes, categories, locations, timeZone }) }); const value = await response.json(); if (!response.ok) { setError(value.error || "Unable to save settings."); return; } setMessage("Event settings saved."); }
  return <section className="mt-8 max-w-3xl rounded-2xl border border-ink/10 bg-white p-6 shadow-sm"><div className="grid gap-5"><p className="rounded-xl bg-mist/50 p-4 text-sm text-ink/65">Event types are used by the calendar and reports. A type that is already used by an event cannot be deleted.</p><ListEditor label="Event types" placeholder="Add event type" values={eventTypes} onChange={setEventTypes} /><ListEditor label="Categories" placeholder="Add category" values={categories} onChange={setCategories} /><ListEditor label="Locations" placeholder="Add location" values={locations} onChange={setLocations} /><fieldset className="rounded-xl border border-ink/10 p-4"><legend className="px-1 text-sm font-semibold">Event timezone</legend><select value={timeZone} onChange={(event) => setTimeZone(event.target.value)} className="focus-ring mt-2 w-full rounded-lg border border-ink/15 px-3 py-2"><option value="America/Chicago">Central Time (US & Canada)</option><option value="America/New_York">Eastern Time (US & Canada)</option><option value="America/Denver">Mountain Time (US & Canada)</option><option value="America/Los_Angeles">Pacific Time (US & Canada)</option><option value="UTC">UTC</option></select></fieldset><Button type="button" onClick={() => void save()}>Save settings</Button>{message && <Notification variant="success">{message}</Notification>}{error && <Notification variant="danger">{error}</Notification>}</div></section>;
}
