"use client";

import { useEffect, useState } from "react";
import { Button, Notification } from "@/components/ui";
import { EVENT_REPORT_COLUMNS, EVENT_REPORT_TYPES, eventReportPreset, type EventReportType } from "@/lib/event-reporting";

type Condition = { field: string; operator: string; value: string };
type VolunteerGroup = { id: string; name: string };
type ScheduleCriteria = { dateFrom?: string; dateTo?: string; eventLimit?: string; volunteerGroupIds?: string[] };
type Report = { id: string; name: string; description: string | null; reportType: string; criteria: { conditions?: Condition[]; match?: "all" | "any"; chart?: boolean; chartOnly?: boolean; chartType?: "bar" | "line" | "pie" }; columns: { key: string; label: string }[]; sort?: { key: string; direction: "asc" | "desc" }[]; grouping?: { key?: string; direction?: "asc" | "desc" }; visibility: string };
const filterFields = EVENT_REPORT_COLUMNS.map((column) => [column.key, column.label]);
const operators = [
  ["equals", "equals"],
  ["not_equals", "does not equal"],
  ["contains", "contains"],
  ["greater_than", "greater than"],
  ["less_than", "less than"],
  ["greater_or_equal", "greater than or equal to"],
  ["less_or_equal", "less than or equal to"]
];
const filterValues: Record<string, string[]> = {
  eventStatus: ["SCHEDULED", "COMPLETED", "CANCELLED"],
  attendanceStatus: ["PRESENT", "ABSENT", "EXCUSED"],
  assignmentSource: ["ROTATION", "OVERRIDE"]
};

export function EventReportManager() {
  const [reports, setReports] = useState<Report[]>([]);
  const [editing, setEditing] = useState<string | null>(null);
  const [form, setForm] = useState({ name: "", description: "", reportType: "event-list" as EventReportType, visibility: "PRIVATE", match: "all" as "all" | "any", conditions: [] as Condition[], columns: EVENT_REPORT_COLUMNS, sortKey: "eventStartsAt", sortDirection: "desc" as "asc" | "desc", groupingKey: "eventStatus", groupingDirection: "asc" as "asc" | "desc", chart: true, chartOnly: false, chartType: "bar" as "bar" | "line" | "pie" });
  const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const [eventTypeValues, setEventTypeValues] = useState<string[]>(["Worship", "Class", "Fellowship", "Outreach", "Meeting", "Other"]);
  const [volunteerGroups, setVolunteerGroups] = useState<VolunteerGroup[]>([]);
  const [schedule, setSchedule] = useState({ dateFrom: "", dateTo: "", eventLimit: "", groupIds: [] as string[] });
  async function load() { const response = await fetch("/api/events/reports", { cache: "no-store" }); const value = await response.json(); if (response.ok) setReports(value.reports ?? []); else setError(value.error ?? "Unable to load reports."); }
  async function importReports(event: React.ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; event.target.value = ""; if (!file) return; try { const response = await fetch("/api/events/reports/import", { method: "POST", headers: { "Content-Type": "application/json" }, body: await file.text() }); const value = await response.json(); if (!response.ok) { setError(value.error ?? "Unable to import reports."); return; } setMessage(`${value.reports?.length ?? 0} report(s) imported.`); await load(); window.dispatchEvent(new CustomEvent("event-reports-updated")); } catch { setError("The selected report file could not be read."); } }
  useEffect(() => { void load(); void Promise.all([fetch("/api/events/settings"), fetch("/api/membership/volunteer-groups")]).then(async ([settingsResponse, groupsResponse]) => { const settings = await settingsResponse.json(); const groups = await groupsResponse.json(); if (settings.settings?.eventTypes?.length) setEventTypeValues(settings.settings.eventTypes); setVolunteerGroups(groups.groups ?? []); }); }, []);
  function reset() { setEditing(null); setSchedule({ dateFrom: "", dateTo: "", eventLimit: "", groupIds: [] }); setForm({ name: "", description: "", reportType: "event-list", visibility: "PRIVATE", match: "all", conditions: [], columns: EVENT_REPORT_COLUMNS, sortKey: "eventStartsAt", sortDirection: "desc", groupingKey: "eventStatus", groupingDirection: "asc", chart: true, chartOnly: false, chartType: "bar" }); }
  function chooseType(reportType: EventReportType) { const preset = eventReportPreset(reportType); setForm((current) => ({ ...current, reportType, columns: reportType === "volunteer-schedule" ? [{ key: "eventDate", label: "Event date" }] : EVENT_REPORT_COLUMNS.filter((column) => preset.columns.includes(column.key)), sortKey: preset.sortKey, sortDirection: preset.sortDirection, groupingKey: preset.groupingKey })); }
  function edit(report: Report) { const sort = report.sort?.[0]; const criteria = report.criteria as typeof report.criteria & ScheduleCriteria; setEditing(report.id); setSchedule({ dateFrom: criteria.dateFrom ?? "", dateTo: criteria.dateTo ?? "", eventLimit: criteria.eventLimit ?? "", groupIds: criteria.volunteerGroupIds ?? [] }); setForm({ name: report.name, description: report.description ?? "", reportType: report.reportType as EventReportType, visibility: report.visibility, match: report.criteria?.match ?? "all", conditions: report.criteria?.conditions ?? [], columns: report.columns?.length ? report.columns : EVENT_REPORT_COLUMNS, sortKey: sort?.key ?? "eventStartsAt", sortDirection: sort?.direction ?? "desc", groupingKey: report.grouping?.key ?? "", groupingDirection: report.grouping?.direction ?? "asc", chart: report.criteria?.chart !== false, chartOnly: report.criteria?.chartOnly === true, chartType: report.criteria?.chartType ?? "bar" }); }
  function addFilter() { setForm((current) => ({ ...current, conditions: [...current.conditions, { field: "eventStatus", operator: "equals", value: "SCHEDULED" }] })); }
  function renderFilterValue(condition: Condition, index: number) {
    const values = condition.field === "eventType" ? eventTypeValues : condition.field === "volunteerGroup" ? volunteerGroups.map((group) => group.name) : filterValues[condition.field];
    if (values) return <select value={condition.value} onChange={(event) => setForm({ ...form, conditions: form.conditions.map((item, itemIndex) => itemIndex === index ? { ...item, value: event.target.value } : item) })} className="focus-ring rounded-lg border border-ink/15 px-2 py-2 text-sm"><option value="">Choose a value</option>{values.map((value) => <option key={value} value={value}>{value}</option>)}</select>;
    return <input value={condition.value} onChange={(event) => setForm({ ...form, conditions: form.conditions.map((item, itemIndex) => itemIndex === index ? { ...item, value: event.target.value } : item) })} className="focus-ring rounded-lg border border-ink/15 px-2 py-2 text-sm" placeholder="Value" />;
  }
  async function save(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setError(""); setMessage("");
    const criteria = { conditions: form.conditions, match: form.match, dateFrom: schedule.dateFrom, dateTo: schedule.dateTo, chart: form.chart, chartOnly: form.chartOnly, chartType: form.chartType, ...(form.reportType === "volunteer-schedule" ? { eventLimit: schedule.eventLimit, volunteerGroupIds: schedule.groupIds } : {}) };
    const body = { name: form.name, description: form.description, reportType: form.reportType, visibility: form.visibility, criteria, columns: form.columns, sort: [{ key: form.sortKey, direction: form.sortDirection }], grouping: form.groupingKey ? { key: form.groupingKey, direction: form.groupingDirection } : {} };
    const response = await fetch(editing ? `/api/events/reports/${editing}` : "/api/events/reports", { method: editing ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
    const value = await response.json(); if (!response.ok) { setError(value.error ?? "Unable to save report."); return; }
    setMessage(editing ? "Report updated." : "Report saved."); reset(); await load(); window.dispatchEvent(new CustomEvent("event-reports-updated", { detail: { id: value.report?.id } }));
  }
  function preview() { const criteria = { conditions: form.conditions, match: form.match, dateFrom: schedule.dateFrom, dateTo: schedule.dateTo, chart: form.chart, chartOnly: form.chartOnly, chartType: form.chartType, ...(form.reportType === "volunteer-schedule" ? { eventLimit: schedule.eventLimit, volunteerGroupIds: schedule.groupIds } : {}) }; window.dispatchEvent(new CustomEvent("event-report-preview", { detail: { name: form.name.trim() || "One-time event report", reportType: form.reportType, criteria, columns: form.columns, sort: [{ key: form.sortKey, direction: form.sortDirection }], grouping: form.groupingKey ? { key: form.groupingKey, direction: form.groupingDirection } : {} } })); }
  async function remove(report: Report) { if (!window.confirm(`Delete the "${report.name}" report?`)) return; const response = await fetch(`/api/events/reports/${report.id}`, { method: "DELETE" }); if (response.ok) { setMessage("Report deleted."); await load(); } }
  async function duplicate(report: Report) { await fetch("/api/events/reports", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: `${report.name} (Copy)`.slice(0, 120), description: report.description ?? "", reportType: report.reportType, visibility: "PRIVATE", criteria: report.criteria, columns: report.columns, sort: report.sort ?? [], grouping: report.grouping ?? {} }) }); setMessage("Report duplicated."); await load(); }
  return <div className="mt-8 grid gap-8 lg:grid-cols-[minmax(0,1.15fr)_minmax(19rem,0.85fr)]">
    <section className="rounded-2xl border border-ink/10 bg-white p-6 shadow-sm"><div className="flex items-center justify-between gap-3"><div><h2 className="font-serif text-2xl">{editing ? "Edit report" : "Create a report"}</h2><p className="mt-1 text-sm text-ink/60">Save reusable filters, columns, sorting, and presentation preferences.</p></div>{editing && <Button type="button" variant="default" onClick={reset}>Cancel</Button>}</div>
      <form onSubmit={(event) => void save(event)} className="mt-5 grid gap-4">
        <label className="grid gap-1 text-sm font-semibold">Report name<input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} className="focus-ring rounded-lg border border-ink/15 px-3 py-2 font-normal" placeholder="e.g. Upcoming Sunday attendance" /></label>
        <label className="grid gap-1 text-sm font-semibold">Description<textarea value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} className="focus-ring min-h-20 rounded-lg border border-ink/15 px-3 py-2 font-normal" /></label>
        <div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-1 text-sm font-semibold">Report type<select value={form.reportType} onChange={(event) => chooseType(event.target.value as EventReportType)} className="focus-ring rounded-lg border border-ink/15 px-3 py-2 font-normal">{EVENT_REPORT_TYPES.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label><label className="grid gap-1 text-sm font-semibold">Visibility<select value={form.visibility} onChange={(event) => setForm({ ...form, visibility: event.target.value })} className="focus-ring rounded-lg border border-ink/15 px-3 py-2 font-normal"><option value="PRIVATE">Only me</option><option value="EVENT_MANAGERS">Event managers</option></select></label></div>
        <fieldset className="rounded-xl border border-ink/10 p-4"><legend className="px-1 text-sm font-semibold">Event date range</legend><div className="grid gap-4 sm:grid-cols-3"><label className="grid gap-1 text-sm font-semibold">From date<input type="date" value={schedule.dateFrom} onChange={(event) => setSchedule({ ...schedule, dateFrom: event.target.value })} className="focus-ring rounded-lg border border-ink/15 px-2 py-2 font-normal" /></label><label className="grid gap-1 text-sm font-semibold">To date<input type="date" value={schedule.dateTo} onChange={(event) => setSchedule({ ...schedule, dateTo: event.target.value })} className="focus-ring rounded-lg border border-ink/15 px-2 py-2 font-normal" /></label>{form.reportType === "volunteer-schedule" && <label className="grid gap-1 text-sm font-semibold">Maximum events<input type="number" min="1" value={schedule.eventLimit} onChange={(event) => setSchedule({ ...schedule, eventLimit: event.target.value })} className="focus-ring rounded-lg border border-ink/15 px-2 py-2 font-normal" placeholder="All matching events" /></label>}</div>{form.reportType === "volunteer-schedule" && <div className="mt-4 grid gap-2"><span className="text-sm font-semibold">Volunteer groups</span>{volunteerGroups.length ? volunteerGroups.map((group) => <label key={group.id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={schedule.groupIds.includes(group.id)} onChange={(event) => { const groupIds = event.target.checked ? [...schedule.groupIds, group.id] : schedule.groupIds.filter((id) => id !== group.id); setSchedule({ ...schedule, groupIds }); setForm({ ...form, columns: [{ key: "eventDate", label: "Event date" }, ...volunteerGroups.filter((item) => groupIds.includes(item.id)).map((item) => ({ key: `group:${item.id}`, label: item.name }))] }); }} />{group.name}</label>) : <span className="text-sm text-ink/60">No volunteer groups found.</span>}</div>}</fieldset>
        <p className="text-xs text-ink/55">Absentee reports treat roster members without a saved attendance record as ABSENT. This matches the attendance workflow, which defaults unrecorded roster members to absent.</p><div className="rounded-xl border border-ink/10 p-4"><div className="flex items-center justify-between"><h3 className="font-semibold">Filters</h3><div className="flex gap-2"><select value={form.match} onChange={(event) => setForm({ ...form, match: event.target.value as "all" | "any" })} className="focus-ring rounded-lg border border-ink/15 px-2 py-1 text-sm"><option value="all">Match all</option><option value="any">Match any</option></select><button type="button" onClick={addFilter} className="focus-ring rounded-full border border-coral px-3 py-1 text-sm font-semibold text-coral">Add filter</button></div></div><div className="mt-3 grid gap-2">{form.conditions.map((condition, index) => <div className="grid gap-2 sm:grid-cols-[1fr_1fr_1fr_auto]" key={`${condition.field}-${index}`}><select value={condition.field} onChange={(event) => { const field = event.target.value; const values = field === "eventType" ? eventTypeValues : field === "volunteerGroup" ? volunteerGroups.map((group) => group.name) : filterValues[field]; setForm({ ...form, conditions: form.conditions.map((item, itemIndex) => itemIndex === index ? { ...item, field, value: values?.[0] ?? "" } : item) }); }} className="focus-ring rounded-lg border border-ink/15 px-2 py-2 text-sm">{filterFields.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select value={condition.operator} onChange={(event) => setForm({ ...form, conditions: form.conditions.map((item, itemIndex) => itemIndex === index ? { ...item, operator: event.target.value } : item) })} className="focus-ring rounded-lg border border-ink/15 px-2 py-2 text-sm">{operators.map(([value, label]) =>         <option key={value} value={value}>{label}</option>)}</select>{renderFilterValue(condition, index)}<button type="button" onClick={() => setForm({ ...form, conditions: form.conditions.filter((_, itemIndex) => itemIndex !== index) })} className="focus-ring rounded-lg px-2 text-sm font-semibold text-coral">Remove</button></div>)}</div></div>
        {form.reportType !== "volunteer-schedule" && <fieldset className="rounded-xl border border-ink/10 p-4"><legend className="px-1 text-sm font-semibold">Columns</legend><div className="grid gap-2 sm:grid-cols-2">{EVENT_REPORT_COLUMNS.map((column) => <label key={column.key} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.columns.some((item) => item.key === column.key)} onChange={(event) => setForm({ ...form, columns: event.target.checked ? [...form.columns, column] : form.columns.filter((item) => item.key !== column.key) })} />{column.label}</label>)}</div></fieldset>}
        <div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-1 text-sm font-semibold">Sort by<select value={form.sortKey} onChange={(event) => setForm({ ...form, sortKey: event.target.value })} className="focus-ring rounded-lg border border-ink/15 px-2 py-2 text-sm">{form.reportType === "volunteer-schedule" && <option value="eventDate">Event date</option>}{EVENT_REPORT_COLUMNS.map((column) => <option key={column.key} value={column.key}>{column.label}</option>)}</select></label><label className="grid gap-1 text-sm font-semibold">Direction<select value={form.sortDirection} onChange={(event) => setForm({ ...form, sortDirection: event.target.value as "asc" | "desc" })} className="focus-ring rounded-lg border border-ink/15 px-2 py-2 text-sm"><option value="asc">Ascending</option><option value="desc">Descending</option></select></label></div>
        <div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-1 text-sm font-semibold">Group by<select value={form.groupingKey} onChange={(event) => setForm({ ...form, groupingKey: event.target.value })} className="focus-ring rounded-lg border border-ink/15 px-2 py-2 text-sm"><option value="">No grouping</option>{EVENT_REPORT_COLUMNS.map((column) => <option key={column.key} value={column.key}>{column.label}</option>)}</select></label><label className="grid gap-1 text-sm font-semibold">Group direction<select value={form.groupingDirection} onChange={(event) => setForm({ ...form, groupingDirection: event.target.value as "asc" | "desc" })} className="focus-ring rounded-lg border border-ink/15 px-2 py-2 text-sm"><option value="asc">Ascending</option><option value="desc">Descending</option></select></label></div>
        <fieldset className="rounded-xl border border-ink/10 p-4"><legend className="px-1 text-sm font-semibold">Chart</legend><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={form.chart} onChange={(event) => setForm({ ...form, chart: event.target.checked, chartOnly: event.target.checked ? form.chartOnly : false })} />        Enable chart in results</label>{form.chart && <><label className="mt-3 flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={form.chartOnly} onChange={(event) => setForm({ ...form, chartOnly: event.target.checked })} />Show chart only (hide table)</label><label className="mt-3 grid gap-1 text-sm font-semibold">Chart type<select value={form.chartType} onChange={(event) => setForm({ ...form, chartType: event.target.value as "bar" | "line" | "pie" })} className="focus-ring rounded-lg border border-ink/15 px-2 py-2 text-sm"><option value="bar">Bar</option><option value="line">Line</option><option value="pie">Pie</option></select></label></>}</fieldset>
        <div className="flex flex-wrap gap-2"><Button type="submit">{editing ? "Update report" : "Save report"}</Button><Button type="button" variant="default" onClick={preview}>Run now</Button></div>{message && <Notification variant="success">{message}</Notification>}{error && <Notification variant="danger">{error}</Notification>}
      </form>
    </section>
    <section className="rounded-2xl border border-ink/10 bg-white p-6 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-serif text-2xl">Saved reports</h2><div className="flex flex-wrap gap-2"><a href="/api/events/reports/export" className="focus-ring rounded-full border border-ink/20 px-3 py-2 text-sm font-semibold">Export definitions</a><label className="focus-ring cursor-pointer rounded-full border border-ink/20 px-3 py-2 text-sm font-semibold">Import definitions<input type="file" accept="application/json,.json" onChange={(event) => void importReports(event)} className="sr-only" /></label></div></div><div className="mt-5 grid gap-3">{reports.length ? reports.map((report) => <div className="rounded-xl border border-ink/10 p-4" key={report.id}><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold">{report.name}</h3><p className="mt-1 text-xs text-ink/55">{EVENT_REPORT_TYPES.find((item) => item.value === report.reportType)?.label ?? report.reportType} · {report.visibility === "PRIVATE" ? "Private" : "Event managers"}</p></div></div><div className="mt-3 flex flex-wrap gap-2"><button type="button" onClick={() => window.dispatchEvent(new CustomEvent("event-report-run", { detail: { id: report.id } }))} className="focus-ring rounded-full bg-coral px-3 py-2 text-sm font-semibold text-white">Run</button><button type="button" onClick={() => window.location.assign(`/admin/report-automations?reportId=${encodeURIComponent(report.id)}`)} className="focus-ring rounded-full border border-coral px-3 py-2 text-sm font-semibold text-coral">Automate</button><button type="button" onClick={() => edit(report)} className="focus-ring rounded-full border border-ink/20 px-3 py-2 text-sm font-semibold">Edit</button><button type="button" onClick={() => void duplicate(report)} className="focus-ring rounded-full border border-coral px-3 py-2 text-sm font-semibold text-coral">Duplicate</button><button type="button" onClick={() => void remove(report)} className="focus-ring rounded px-2 py-1 text-sm font-semibold text-coral">Delete</button></div></div>) : <p className="text-sm text-ink/60">No event reports yet.</p>}</div></section>
  </div>;
}
