"use client";
import { useEffect, useState } from "react";
import { Card, Container, Notification } from "@/components/ui";
type Plan = { id: string; name: string; description: string | null; monthlyPrice: string; annualPrice: string; currency: string; providers: { STRIPE: boolean; PAYPAL: boolean } };
export default function BillingPage() {
  const [plans, setPlans] = useState<Plan[]>([]); const [provider, setProvider] = useState("STRIPE"); const [interval, setInterval] = useState("MONTHLY"); const [planId, setPlanId] = useState(""); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  useEffect(() => { void fetch("/api/billing/plans", { cache: "no-store" }).then(async (response) => { const value = await response.json(); if (!response.ok) throw new Error(value.error); setPlans(value.plans); setPlanId(value.plans[0]?.id ?? ""); }).catch((reason) => setError(reason instanceof Error ? reason.message : "Unable to load billing plans.")); }, []);
  async function start() { setError(""); setMessage(""); const response = await fetch("/api/billing/subscribe", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ planId, provider, interval }) }); const value = await response.json(); if (!response.ok) { setError(value.error); return; } if (value.subscription?.checkoutUrl) { window.location.assign(value.subscription.checkoutUrl); return; } setMessage("Checkout initiation recorded. Payment remains pending provider confirmation."); }
  return <main className="min-h-screen bg-sand py-10 sm:py-14"><Container><p className="text-sm font-semibold uppercase tracking-[0.2em] text-coral">Site administration</p><h1 className="mt-2 font-serif text-4xl">Subscription plans</h1><p className="mt-3 max-w-2xl text-sm text-ink/60">Choose a plan and provider to begin checkout. This site never collects card or PayPal credentials and cannot mark payment successful.</p>{error && <Notification variant="danger" className="mt-6">{error}</Notification>}{message && <Notification variant="success" className="mt-6">{message}</Notification>}<div className="mt-8 grid gap-5">{plans.map((plan) => <Card key={plan.id} className="p-6"><h2 className="font-serif text-2xl">{plan.name}</h2><p className="mt-2 text-sm text-ink/60">{plan.description ?? "Subscription plan"}</p><p className="mt-3 text-sm">{plan.currency} {interval === "MONTHLY" ? plan.monthlyPrice : plan.annualPrice} / {interval.toLowerCase()}</p><div className="mt-4 flex flex-wrap gap-3"><button type="button" onClick={() => setPlanId(plan.id)} className={`focus-ring rounded-lg border px-3 py-2 text-sm ${planId === plan.id ? "border-coral bg-coral/10" : "border-ink/15 bg-white"}`}>Select plan</button>{(["STRIPE", "PAYPAL"] as const).map((value) => <button key={value} type="button" disabled={!plan.providers[value]} onClick={() => { setPlanId(plan.id); setProvider(value); }} className="focus-ring rounded-lg border border-ink/15 px-3 py-2 text-sm disabled:cursor-not-allowed disabled:opacity-40">{value} {!plan.providers[value] && "(unavailable)"}</button>)}</div></Card>)}</div>{plans.length > 0 && <Card className="mt-6 p-5"><label className="mr-4 text-sm font-semibold">Billing interval <select value={interval} onChange={(event) => setInterval(event.target.value)} className="focus-ring rounded border px-2 py-1"><option>MONTHLY</option><option>ANNUAL</option></select></label><button type="button" onClick={() => void start()} className="focus-ring rounded-lg bg-coral px-4 py-2 text-sm font-semibold text-white">Begin provider checkout</button></Card>}</Container></main>;
}
