DO $$ BEGIN
  CREATE TYPE "TenantLifecycleStatus" AS ENUM ('PROVISIONING', 'ACTIVE', 'SUSPENDED', 'DISABLED');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "OnboardingStatus" AS ENUM ('PENDING_VERIFICATION', 'IN_PROGRESS', 'COMPLETE');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

ALTER TABLE "Church"
  ADD COLUMN IF NOT EXISTS "siteUrl" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "tagline" TEXT NOT NULL DEFAULT 'A place to belong.',
  ADD COLUMN IF NOT EXISTS "addressStreet" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "phone" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "email" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "taxId" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "enabledModules" JSONB NOT NULL DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS "lifecycleStatus" "TenantLifecycleStatus" NOT NULL DEFAULT 'ACTIVE',
  ADD COLUMN IF NOT EXISTS "onboardingStatus" "OnboardingStatus" NOT NULL DEFAULT 'PENDING_VERIFICATION',
  ADD COLUMN IF NOT EXISTS "onboardingStep" TEXT;

CREATE INDEX "Church_lifecycleStatus_idx" ON "Church"("lifecycleStatus");

ALTER TYPE "OnboardingStatus" ADD VALUE IF NOT EXISTS 'SUBSCRIPTION_REQUIRED';
ALTER TYPE "OnboardingStatus" ADD VALUE IF NOT EXISTS 'PROVISIONING';
ALTER TYPE "OnboardingStatus" ADD VALUE IF NOT EXISTS 'SITE_SETUP';
