"use client";
import { FormEvent, useEffect, useState } from "react";
import { Card, Container, Notification } from "@/components/ui";
import { GlobalAdminBackLink } from "@/app/global-admin/back-link";
type ConfigRow = { provider: string; environment: string; configured: boolean; webhookConfigured: boolean; apiBaseUrl: string | null; updatedAt: string };
export default function Config() {
  const [rows, setRows] = useState<ConfigRow[]>([]); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [provider, setProvider] = useState("STRIPE"); const [environment, setEnvironment] = useState("TEST"); const [values, setValues] = useState<Record<string, string>>({});
  useEffect(() => { fetch("/api/global-admin/billing/config", { cache: "no-store" }).then(async (r) => { const v = await r.json(); if (!r.ok) throw new Error(v.error); setRows(v.configurations); }).catch((e) => setError(e instanceof Error ? e.message : "Unable to load configuration.")); }, []);
  async function save(event: FormEvent) { event.preventDefault(); setError(""); setMessage(""); const response = await fetch("/api/global-admin/billing/config", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ provider, environment, ...values }) }); const result = await response.json(); if (!response.ok) { setError(result.error); return; } setRows(result.configurations); setValues({}); setMessage("Configuration saved. Secrets are stored encrypted and will not be shown."); }
  const field = (name: string, label: string, type = "password") => <label className="grid gap-1 text-sm"><span>{label}</span><input type={type} value={values[name] || ""} onChange={(e) => setValues({ ...values, [name]: e.target.value })} placeholder="Leave blank to preserve existing value" className="focus-ring rounded border border-ink/15 bg-white px-3 py-2" autoComplete="off" /></label>;
  return <main className="min-h-screen bg-sand py-10"><Container><div className="flex justify-end"><GlobalAdminBackLink /></div><h1 className="mt-8 font-serif text-4xl">Billing provider configuration</h1><p className="mt-3 max-w-2xl text-sm text-ink/60">Secrets are encrypted at rest using BILLING_CONFIG_MASTER_KEY and are never returned. Environment variables remain a fallback.</p>{error && <Notification variant="danger" className="mt-5">{error}</Notification>}{message && <Notification variant="success" className="mt-5">{message}</Notification>}<Card className="mt-6 p-6"><form onSubmit={save} className="grid gap-4"><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-1 text-sm"><span>Provider</span><select value={provider} onChange={(e) => setProvider(e.target.value)} className="rounded border px-3 py-2"><option>STRIPE</option><option>PAYPAL</option></select></label><label className="grid gap-1 text-sm"><span>Environment</span><select value={environment} onChange={(e) => setEnvironment(e.target.value)} className="rounded border px-3 py-2"><option>TEST</option><option>LIVE</option></select></label></div>{provider === "STRIPE" ? <>{field("secretKey", "Stripe secret key")}{field("webhookSecret", "Stripe webhook secret")}</> : <>{field("clientId", "PayPal client ID", "text")}{field("clientSecret", "PayPal client secret")}{field("webhookId", "PayPal webhook ID", "text")}{field("apiBaseUrl", "PayPal API base URL", "url")}</>}<button className="focus-ring rounded bg-ink px-4 py-2 text-sm font-semibold text-white">Save provider configuration</button></form></Card><div className="mt-6 grid gap-4 md:grid-cols-2">{rows.map((row) => <Card key={`${row.provider}-${row.environment}`} className="p-5"><strong>{row.provider} · {row.environment}</strong><p className="mt-2 text-sm text-ink/60">Credentials: {row.configured ? "configured" : "not configured"} · Webhook: {row.webhookConfigured ? "configured" : "not configured"}{row.apiBaseUrl ? ` · API: ${row.apiBaseUrl}` : ""}</p></Card>)}</div></Container></main>;
}
