"use client";

import { useEffect, useState } from "react";
import type { FormEvent } from "react";
import { Card, Container } from "@/components/ui";

type Settings = {
  loginProtectionEnabled: boolean; maxFailedAttempts: number; lockoutMinutes: number; captchaMode: string;
  emailMfaEnabled: boolean; smsMfaEnabled: boolean; authenticatorMfaEnabled: boolean;
  recaptchaSiteKey: string; recaptchaSecret: string; recaptchaConfigured: boolean;
  smsProvider: "twilio" | "vonage" | "aws-sns"; smsAccountId: string; smsAuthSecret: string; smsConfigured: boolean; smsFrom: string; totpIssuer: string;
};
const initial: Settings = { loginProtectionEnabled: true, maxFailedAttempts: 5, lockoutMinutes: 15, captchaMode: "off", emailMfaEnabled: false, smsMfaEnabled: false, authenticatorMfaEnabled: false, recaptchaSiteKey: "", recaptchaSecret: "", recaptchaConfigured: false, smsProvider: "twilio", smsAccountId: "", smsAuthSecret: "", smsConfigured: false, smsFrom: "", totpIssuer: "St. Paul's Site" };

export default function SecuritySettingsPage() {
  const [settings, setSettings] = useState(initial);
  const [message, setMessage] = useState("");
  useEffect(() => { void fetch("/api/security-settings").then((response) => response.json()).then((value) => setSettings((current) => ({ ...current, ...value, recaptchaSecret: "", smsAuthSecret: "" }))).catch(() => setMessage("Unable to load settings.")); }, []);
  function change<K extends keyof Settings>(key: K, value: Settings[K]) { setSettings((current) => ({ ...current, [key]: value })); }
  async function save(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const response = await fetch("/api/security-settings", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(settings) });
    setMessage(response.ok ? "Security settings saved." : "Unable to save security settings.");
    if (response.ok) setSettings((current) => ({ ...current, recaptchaSecret: "", smsAuthSecret: "" }));
  }
  return <main><Container className="py-10 sm:py-14"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-coral">Security</p><h1 className="mt-2 font-serif text-4xl">Settings</h1><form onSubmit={(event) => void save(event)} className="mt-8 grid gap-6 xl:grid-cols-2">
    <Card><h2 className="font-serif text-2xl">Login protection</h2><p className="mt-2 text-sm text-ink/60">Basic controls that apply to every account.</p><div className="mt-5 grid gap-4"><label className="flex items-center gap-3 text-sm font-semibold"><input type="checkbox" checked={settings.loginProtectionEnabled} onChange={(event) => change("loginProtectionEnabled", event.target.checked)} /> Enable login protection</label><label className="grid gap-1 text-sm font-semibold">Failed attempts before lockout<input type="number" min={1} max={20} value={settings.maxFailedAttempts} onChange={(event) => change("maxFailedAttempts", Number(event.target.value))} className="focus-ring rounded-lg border border-ink/15 px-3 py-2 font-normal" /></label><label className="grid gap-1 text-sm font-semibold">Lockout time (minutes)<input type="number" min={1} max={1440} value={settings.lockoutMinutes} onChange={(event) => change("lockoutMinutes", Number(event.target.value))} className="focus-ring rounded-lg border border-ink/15 px-3 py-2 font-normal" /></label></div></Card>
    <Card><h2 className="font-serif text-2xl">Human verification</h2><p className="mt-2 text-sm text-ink/60">Captcha is global and applies at sign-in. <a className="text-coral underline" href="https://www.google.com/recaptcha/admin" target="_blank" rel="noreferrer">Get Google reCAPTCHA keys</a>.</p><label className="mt-5 grid gap-1 text-sm font-semibold">Captcha method<select value={settings.captchaMode} onChange={(event) => change("captchaMode", event.target.value)} className="focus-ring rounded-lg border border-ink/15 px-3 py-2 font-normal"><option value="off">Off</option><option value="challenge">Built-in challenge</option><option value="recaptcha-v3">Google reCAPTCHA v3</option></select></label><div className="mt-4 grid gap-4"><label className="grid gap-1 text-sm font-semibold">Site key<input value={settings.recaptchaSiteKey} onChange={(event) => change("recaptchaSiteKey", event.target.value)} className="focus-ring rounded-lg border border-ink/15 px-3 py-2 font-normal" /></label><label className="grid gap-1 text-sm font-semibold">Secret key{settings.recaptchaConfigured && <span className="font-normal text-ink/50">(configured; leave blank to keep)</span>}<input type="password" value={settings.recaptchaSecret} onChange={(event) => change("recaptchaSecret", event.target.value)} className="focus-ring rounded-lg border border-ink/15 px-3 py-2 font-normal" /></label></div></Card>
    <Card><h2 className="font-serif text-2xl">Text message 2FA</h2><p className="mt-2 text-sm text-ink/60">Choose a provider and enter its server-side credentials. <a className="text-coral underline" href="https://www.twilio.com/console" target="_blank" rel="noreferrer">Twilio</a> is recommended; alternatives are <a className="text-coral underline" href="https://dashboard.nexmo.com/" target="_blank" rel="noreferrer">Vonage</a> and <a className="text-coral underline" href="https://console.aws.amazon.com/sns/" target="_blank" rel="noreferrer">AWS SNS</a>.</p><label className="mt-5 flex items-center gap-3 text-sm font-semibold"><input type="checkbox" checked={settings.smsMfaEnabled} onChange={(event) => change("smsMfaEnabled", event.target.checked)} /> Make text 2FA available</label><label className="mt-4 grid gap-1 text-sm font-semibold">Provider<select value={settings.smsProvider} onChange={(event) => change("smsProvider", event.target.value as Settings["smsProvider"])} className="focus-ring rounded-lg border border-ink/15 px-3 py-2 font-normal"><option value="twilio">Twilio (Account SID + Auth Token)</option><option value="vonage">Vonage (API key + secret)</option><option value="aws-sns">AWS SNS (access key + secret)</option></select></label><label className="mt-4 grid gap-1 text-sm font-semibold">Account/API ID<input value={settings.smsAccountId} onChange={(event) => change("smsAccountId", event.target.value)} className="focus-ring rounded-lg border border-ink/15 px-3 py-2 font-normal" /></label><label className="mt-4 grid gap-1 text-sm font-semibold">Secret{settings.smsConfigured && <span className="font-normal text-ink/50">(configured; leave blank to keep)</span>}<input type="password" value={settings.smsAuthSecret} onChange={(event) => change("smsAuthSecret", event.target.value)} className="focus-ring rounded-lg border border-ink/15 px-3 py-2 font-normal" /></label><label className="mt-4 grid gap-1 text-sm font-semibold">{settings.smsProvider === "twilio" ? "Twilio phone number" : "Sender ID"}<input value={settings.smsFrom} onChange={(event) => change("smsFrom", event.target.value)} placeholder={settings.smsProvider === "twilio" ? "+15551234567" : "StPauls"} className="focus-ring rounded-lg border border-ink/15 px-3 py-2 font-normal" /></label></Card>
    <Card><h2 className="font-serif text-2xl">Authenticator apps</h2><p className="mt-2 text-sm text-ink/60">Authenticator apps use the open TOTP standard; no vendor API account is required. Users will scan a per-account QR code during enrollment.</p><label className="mt-5 flex items-center gap-3 text-sm font-semibold"><input type="checkbox" checked={settings.authenticatorMfaEnabled} onChange={(event) => change("authenticatorMfaEnabled", event.target.checked)} /> Make authenticator apps available</label><label className="mt-4 grid gap-1 text-sm font-semibold">Issuer name<input value={settings.totpIssuer} onChange={(event) => change("totpIssuer", event.target.value)} className="focus-ring rounded-lg border border-ink/15 px-3 py-2 font-normal" /></label><p className="mt-4 text-xs leading-5 text-ink/50">This label appears in Google Authenticator, Microsoft Authenticator, and compatible apps. Enrollment and recovery codes will be added to user account security settings.</p></Card>
    <div className="xl:col-span-2"><button className="focus-ring rounded-full bg-coral px-5 py-3 text-sm font-semibold text-white" type="submit">Save security settings</button>{message && <p role="status" className="mt-3 text-sm">{message}</p>}</div>
  </form></Container></main>;
}
